/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Sale = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validForm?: string;
  validUntil?: string;
  isActive?: boolean;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  paystackReference?: string;
  paystackTransactionId?: string;
  paystackCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  promoCode?: string;
  currency?: string;
  amountDiscount?: number;
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    price?: number;
    _key: string;
  }>;
  totalPrice?: number;
  metadata?: string;
  aiSummary?: string;
  customerType?: "new" | "returning" | "vip";
  riskLevel?: "low" | "medium" | "high";
  riskFlags?: Array<string>;
  aiAnalyzedAt?: string;
  aiConfidence?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | {
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "file";
    _key: string;
  }>;
  description?: string;
  price?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  rating?: number;
  ratingCount?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Sale | ProductReference | Order | SanityImageAssetReference | SanityFileAssetReference | CategoryReference | Product | SanityImageCrop | SanityImageHotspot | Slug | Post | BlockContent | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/products/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {      ...,      "productCount": count(*[_type == "product" && references(^._id)]),      "productsPreview": *[_type == "product" && references(^._id)] | order(name asc)[0..5]{        ...,        "slug": slug.current      }    }
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  productCount: number;
  productsPreview: Array<{
    _id: string;
    _type: "product";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    slug: string | null;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    gallery?: Array<{
      asset?: SanityFileAssetReference;
      media?: unknown;
      alt?: string;
      _type: "file";
      _key: string;
    } | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }>;
    description?: string;
    price?: number;
    categories?: Array<{
      _key: string;
    } & CategoryReference>;
    stock?: number;
    rating?: number;
    ratingCount?: number;
  }>;
}>;

// Source: ./src/sanity/lib/products/getAllProducts.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[      _type == "product"    ] | order(name asc)
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  rating?: number;
  ratingCount?: number;
}>;

// Source: ./src/sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[      _type == "product" && slug.current == $slug    ] | order(name asc) [0]
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  rating?: number;
  ratingCount?: number;
} | null;

// Source: ./src/sanity/lib/products/searchProductsByName.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product"      && ($searchParam == "" || name match $searchParam)      && ($category == "" || $category in categories[]->slug.current)    ] | order(name asc)
export type PRODUCT_SEARCH_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityFileAssetReference;
    media?: unknown;
    alt?: string;
    _type: "file";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  stock?: number;
  rating?: number;
  ratingCount?: number;
}>;

// Source: ./src/sanity/lib/sales/getActiveSale.ts
// Variable: ACTIVE_SALE_QUERY
// Query: *[_type == "sale" && isActive == true] | order(validFrom desc)[0]
export type ACTIVE_SALE_QUERYResult = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validForm?: string;
  validUntil?: string;
  isActive?: boolean;
} | null;

// Source: ./src/sanity/lib/sales/getActiveSaleByCouponCode.ts
// Variable: ACTIVE_SALE_BY_COUPON_QUERY
// Query: *[_type == "sale"     && isActive == true     && couponCode == $couponCode     ] | order(validFrom desc)[0]
export type ACTIVE_SALE_BY_COUPON_QUERYResult = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validForm?: string;
  validUntil?: string;
  isActive?: boolean;
} | null;

// Source: ./src/sanity/lib/sales/getAllActiveSales.ts
// Variable: ALL_ACTIVE_SALES_QUERY
// Query: *[_type == "sale" && isActive == true] | order(validFrom desc)
export type ALL_ACTIVE_SALES_QUERYResult = Array<{
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validForm?: string;
  validUntil?: string;
  isActive?: boolean;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n    *[_type == \"category\"] | order(title asc) {\n      ...,\n      \"productCount\": count(*[_type == \"product\" && references(^._id)]),\n      \"productsPreview\": *[_type == \"product\" && references(^._id)] | order(name asc)[0..5]{\n        ...,\n        \"slug\": slug.current\n      }\n    }\n    ": ALL_CATEGORIES_QUERYResult;
    "\n    *[\n      _type == \"product\"\n    ] | order(name asc)\n    ": ALL_PRODUCTS_QUERYResult;
    "\n    *[\n      _type == \"product\" && slug.current == $slug\n    ] | order(name asc) [0]\n    ": PRODUCT_BY_ID_QUERYResult;
    "\n    *[_type == \"product\"\n      && ($searchParam == \"\" || name match $searchParam)\n      && ($category == \"\" || $category in categories[]->slug.current)\n    ] | order(name asc)\n    ": PRODUCT_SEARCH_QUERYResult;
    "\n    *[_type == \"sale\" && isActive == true] | order(validFrom desc)[0]\n  ": ACTIVE_SALE_QUERYResult;
    "\n    *[_type == \"sale\" \n    && isActive == true\n     && couponCode == $couponCode\n     ] | order(validFrom desc)[0] \n    ": ACTIVE_SALE_BY_COUPON_QUERYResult;
    "\n    *[_type == \"sale\" && isActive == true] | order(validFrom desc)\n  ": ALL_ACTIVE_SALES_QUERYResult;
  }
}
